version: 2
updates:
  # Enable version updates for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "andkrause"
    # ignore:
    #   - dependency-name: "php"
    #     # Ignore minor versions
    #     update-types: ["version-update:semver-major","version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
