version: 2
updates:
  # Enable version updates for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "andkrause"
    ignore:
      - dependency-name: "php"
        # Ignore PHP 8
        versions: ["8.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
