version: '3'
services:
    web:
        image: andy008/docker-seeddms:6.0.8-3
        ports:
            - 80:80
        volumes:
            - data_volume:/var/www/seeddms/data
            - conf_volume:/var/www/seeddms/conf
            - ext_volume:/var/www/seeddms/www/ext
volumes:
    data_volume:
    conf_volume:
    ext_volume: