version: '3'
services:
    php-fpm:
        image: andy008/php-fpm-seeddms:7.4
        volumes:
            - seeddms:/var/www/seeddms
    nginx:
        image: andy008/nginx:1.16.1-alpine
        ports: 
            - 80:80
        depends_on:
            - php-fpm
        volumes:
            - seeddms:/var/www/seeddms
            - nginxConfig:/etc/nginx/conf.d/
volumes:
    seeddms:
       driver: local
       driver_opts:
          o: bind
          type: none
          device: /Users/andy008/Documents/Servers/RaspberryPi4b/seeddms/docker-seeddms/volumes/seeddms
    nginxConfig:
       driver: local
       driver_opts:
          o: bind
          type: none
          device: /Users/andy008/Documents/Servers/RaspberryPi4b/seeddms/docker-seeddms/volumes/nginxConfig/